# Generated by Django 4.2.5 on 2023-10-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CargarLibro',
            new_name='Libro',
        ),
    ]
